### ISSUE TITLE
QM driver remaining issues for first 0.2 release

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibolab#969]
https://github.com/qiboteam/qibolab/pull/933#issuecomment-2272105877

- [x] Baking: support for durations that are not multiple of 4ns. Now we also need to handle the case of non-integer durations, potentially by casting to `int` and raising a warning. See also discussion in https://github.com/qiboteam/qibolab/pull/979#discussion_r1729266768 (Done in #1005)
- [x] Unrolling: `unroll_sequences` now needs to be called by the driver. (Done in #1008)
- [x] Parallel sweeps: the sweeper structure in the driver is updated with this in mind, however I did not fully implement it for the case len(parallel_sweepers) > 1 mainly because there is no qibocal routine using this. We may end up needing it for all routines if we drop sweeper types (#540). (Done in #1008)

**Comment by stavros11** [comment]
All listed features are now implemented, with the corresponding PRs linked in the first comment.
